### ISSUE TITLE
Disable auto pip 

### ISSUE THREAD

**Issue by ragul-pr** [harshitverma209/android_pip#1]
Could you please. give me clear documentation on how to disable from auto pip.

**Comment by harshitverma209** [comment]
Hello Ragul, if you wish to disable automatic pip, you should use `AndroidPIP().setAutoPipMode(autoEnter:false)`. If there is anything else you need help with, please let me know.

**Comment by ragul-pr** [comment]
Yeah now that's working fine. But still, the pip widget doesn't make returns the pip child instead it returns same widget in pip. Can you please check and the simple pip works fine on this case. this plugin doesn't work as expected.

**Comment by harshitverma209** [comment]
Hi Ragul, please try setting the newly added `useStack` parameter to false.
