### ISSUE TITLE
Update documentation for 1.2.1

### ISSUE THREAD

**Issue by Rohan487** [harshitverma209/android_pip#5]
Hey you need to udpate the documentation for version 1.1.0. Cause the application will broke if someone will upgrade from 1.1.0 to newer versions.

in the PipCallbackHelper.kt , you have changed event type from boolean to PIPDefaultEvent in the newer versions

![image](https://github.com/user-attachments/assets/1e56b1c0-950e-4530-96db-e7adf4eeb555)

But int the documentation you are passing boolean type to the active param

![image](https://github.com/user-attachments/assets/7975b501-e68e-4bd6-a25f-072b0aba58b0)

**Documentation is outdated and is failing the build, kindly update it as soon as possible**

**Comment by Rohan487** [comment]
Also mention its as "breaking changes"

**Comment by harshitverma209** [comment]
Hey, thanks for pointing this out. I have updated the plugin with a newer and simpler way of implementing callbacks and have updated the docs.
